### ISSUE TITLE
add file for matrix addition

### ISSUE THREAD

**Issue by HemangJoshi** [HemangJoshi/hacktoberfet-2022#3]
must be done in c++
the issue will be closed after the first valid pull request but if anyone wants to make changes to the provided solution can make a pull request for the same

**Comment by Tathagat27** [comment]
I would like to do this.

**Comment by Siddr04** [comment]
Can I be assigned to this ?

**Comment by HemangJoshi** [comment]
this task has been completed by another contributer ( @guptashreyas ) but if you any changes in  his solution than you can make  a pull request
