### ISSUE TITLE
add a file for matrix subtraction

### ISSUE THREAD

**Issue by HemangJoshi** [HemangJoshi/hacktoberfet-2022#9]
must be in c++

the issue will be closed after the first valid pull request but if anyone wants to make changes to the provided solution can make a pull request for the same

**Comment by PanwarAyush** [comment]
I am good at algorithms and problem solving. 
please assign this issue to me.

**Comment by HemangJoshi** [comment]
> I am good at algorithms and problem-solving. please assign this issue to me.

there you brother

**Comment by BlackBolt2003** [comment]
May I solve this issue? I'm proficient in C++ language as well as engineering mathematics.

**Comment by HemangJoshi** [comment]
> May I solve this issue? I'm proficient in C++ language as well as engineering mathematics.

although I have already assigned it to someone else, you can also give it a try.
or you can check out other issues in the repo and try them out too.

**Comment by BlackBolt2003** [comment]
Ok, thank you.

**Comment by PanwarAyush** [comment]
Matrix subtraction cpp program added #13
